package com.auto_car.gui;

import com.auto_car.model.Driver;
import com.auto_car.model.Vehicle;
import com.auto_car.repos.DriversRepo;
import com.auto_car.repos.VehicleRepo;

import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;
import java.util.Arrays;

public class FirstForm {
    private JPanel panel1;
    private JTabbedPane tabbedPane1;
    private JTable DriversTable;
    private JTable VehiclesTable;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, BorderLayout.NORTH);
        tabbedPane1 = new JTabbedPane();
        scrollPane1.setViewportView(tabbedPane1);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        tabbedPane1.addTab("Vehicles", panel2);
        final JScrollPane scrollPane2 = new JScrollPane();
        panel2.add(scrollPane2, BorderLayout.CENTER);
        VehiclesTable = new JTable();
        scrollPane2.setViewportView(VehiclesTable);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        tabbedPane1.addTab("Drivers", panel3);
        final JScrollPane scrollPane3 = new JScrollPane();
        panel3.add(scrollPane3, BorderLayout.CENTER);
        DriversTable = new JTable();
        scrollPane3.setViewportView(DriversTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }


    //////////////////////// write here
    public FirstForm() {
        setData();
    }

    public void setData() {
        setDriversTableData();
        setDVehicleTableData();

    }

    private void setDriversTableData() {
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("First Name");
        defaultTableModel.addColumn("Last Name");
        defaultTableModel.addColumn("Id");
        for (Driver driver : DriversRepo.getInstance().getDrivers()) {
            defaultTableModel.addRow(Arrays.asList(driver.getFirstName(), driver.getLastName(), driver.getId()).toArray());
        }
        DriversTable.setModel(defaultTableModel);
    }

        private void setDVehicleTableData() {
            DefaultTableModel defaultTableModel = new DefaultTableModel();
            defaultTableModel.addColumn("LicensePlate");
            defaultTableModel.addColumn("vehicleExpenses");

            for (Vehicle vehicle : VehicleRepo.getInstance().getVehicles()) {
                defaultTableModel.addRow(Arrays.asList(vehicle.getLicensePlate(), vehicle.getVehicleExpenses().getTotalExpenses()).toArray());
            }
            VehiclesTable.setModel(defaultTableModel);
        }
}
