package com.auto_car.gui;

import com.auto_car.model.Driver;
import com.auto_car.repos.DriversRepo;

import javax.swing.*;
import javax.swing.event.TableModelListener;
import javax.swing.table.*;
import java.awt.*;
import java.util.Arrays;

public class FirstForm {
    private JPanel panel1;
    private JTabbedPane tabbedPane1;
    private JTable table1;

    public FirstForm() {
        panel1.add(new JScrollPane(tabbedPane1));
        setData(DriversRepo.getInstance());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        tabbedPane1 = new JTabbedPane();
        panel1.add(tabbedPane1, BorderLayout.CENTER);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        tabbedPane1.addTab("Drivers", panel2);
        table1 = new JTable();
        panel2.add(table1, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }


    ////////////////////////
    public void setData(DriversRepo data) {

        DefaultTableModel defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("First Name");
        defaultTableModel.addColumn("Last Name");
        defaultTableModel.addColumn("Id");
        for (Driver driver : data.getDrivers()) {
            defaultTableModel.addRow(Arrays.asList(driver.getFirstName(), driver.getLastName(), driver.getId()).toArray());
        }
        table1.setModel(defaultTableModel);

    }

    public void getData(DriversRepo data) {
    }

    public boolean isModified(DriversRepo data) {
        return false;
    }
}
