package com.auto_car.gui;

import com.auto_car.model.Driver;
import com.auto_car.repos.DriversRepo;

import javax.swing.*;
import javax.swing.event.TableModelListener;
import javax.swing.table.*;
import java.awt.*;
import java.util.Arrays;

public class FirstForm {
    private JPanel panel1;
    private JTabbedPane tabbedPane1;
    private JTable table1;

    public FirstForm() {
        setData(DriversRepo.getInstance());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, BorderLayout.NORTH);
        tabbedPane1 = new JTabbedPane();
        scrollPane1.setViewportView(tabbedPane1);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        tabbedPane1.addTab("Vehicles", panel2);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        tabbedPane1.addTab("Drivers", panel3);
        final JScrollPane scrollPane2 = new JScrollPane();
        panel3.add(scrollPane2, BorderLayout.CENTER);
        table1 = new JTable();
        scrollPane2.setViewportView(table1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }


    ////////////////////////
    public void setData(DriversRepo data) {

        DefaultTableModel defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("First Name");
        defaultTableModel.addColumn("Last Name");
        defaultTableModel.addColumn("Id");
        for (Driver driver : data.getDrivers()) {
            defaultTableModel.addRow(Arrays.asList(driver.getFirstName(), driver.getLastName(), driver.getId()).toArray());
        }
        table1.setModel(defaultTableModel);

    }

}
